#!/usr/bin/env node
require('longjohn') // long stack traces
var root = require('path').resolve(__dirname, 'src', 'server')
  , app  = require('glagol')(root)
  , log  = app().log.as('init');
app.get('bundler').options = app.get('bundler').get('glagol-options.js')();
module.exports = app;
if (module === require.main) {
  app().main();
  _.electron(); }
