#!/usr/bin/env node
require('longjohn') // long stack traces
var root = require('path').resolve(__dirname, 'src', 'Server')
  , app  = require('glagol')(root)
app.get('Bundler').options = app.get('Bundler').get('glagol-options.js')();
module.exports = app;
if (module === require.main) app().Main();
